version: '3'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/equipress
      - NEXT_PUBLIC_FACT_CHECK_API_URL=http://fact-check-api:5000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb
      - fact-check-api

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  fact-check-api:
    build:
      context: ./fact-check-api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./fact-check-api:/app

volumes:
  mongodb_data:
